#if !canImport(ObjectiveC)
import XCTest

extension ExampleTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ExampleTests = [
        ("testDummy", testDummy),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ExampleTests.__allTests__ExampleTests),
    ]
}
#endif
